### ISSUE TITLE
test_nlp/test_graph failure 

### ISSUE THREAD

**Issue by jgibson517** [uchicago-capp-30320/CivicLens#121]
Here's the error from the test failure @abejburton, might be a statistics problem where algorithm generates slightly different clusters occasionally. 

At index 0 diff: {3, 5, 10, 14, 15, 16, 19, 20, 21, 22, 24, 25, 26, 27} != {0, 1, 2, 4, 6, 7, 8, 9, 11, 12, 13, 17, 18, 23}
  
  Full diff:
    [
  +     {
  +         3,
  +         5,
  +         10,
  +         14,
  +         15,
  +         16,
  +         19,
  +         20,
  +         21,
  +         22,
  +         24,
  +         25,
  +         26,
  +         27,
  +     },
        {
            0,
            1,
            2,
            4,
            6,
            7,
            8,
            9,
            11,
            12,
            13,
            17,
            18,
            23,
        },
  -     {
  -         3,
  -         5,
  -         10,
  -         14,
  -         15,
  -         16,
  -         19,
  -         20,
  -         21,
  -         22,
  -         24,
  -         25,
  -         26,
  -         27,
  -     },
    ]

**Comment by abejburton** [comment]
Fixed this test
