### ISSUE TITLE
Filter the Document Summaries for non-ascii characters

### ISSUE THREAD

**Issue by jchristensonCHI** [uchicago-capp-30320/CivicLens#137]

**Comment by claireboyd** [comment]
this is the transform step to include in the chron job. the main step to add to this script now is the clean string (remove ascii) but this could include other cleaning steps for the db

**Comment by andrewjtdunn** [comment]
This was resolved in a past commit

**Comment by andrewjtdunn** [comment]
This was resolved in a past commit
