### ISSUE TITLE
Build data pipeline between regulations.gov API and database

### ISSUE THREAD

**Issue by andrewjtdunn** [uchicago-capp-30320/CivicLens#15]
General idea for data downloading from API (focused on the initial one-time pull right now):

- [x] Get list of new documents since last data pull
- [x] From that list, get list of documents which are accepting comments
- [x] Get dockets for documents which are accepting comments
- [x] Put docket info in docket table if not already there
- [x] Get list of all documents which are included in those dockets
- [x] Access the text of these documents via general register API
- [x] Put document info, including text, in documents table
- [x] For each document open for commenting, get list of comments on that document (this could be lengthy)
- [x] Put comment info, including text, in comments table
- [x] Access the text of those comments, put in comments text table

To be determined for the initial, one-time pull: how to keep track in an organized way where the process left off when an API key's access was exhausted (that is, hit the limit of what can be pulled within the API restrictions)

**Comment by andrewjtdunn** [comment]
@rezarzky @GregoryHo88 Can you look at the code I've written in this branch? I've made a main method that could be tailored/adapted to what Greg's working on. My code isn't quite ready for a PR, but I want you two to both see it so that we can collaboratively use what I've written to allow us to download data from the API. I haven't tested the INSERT methods yet out of an abundance of concern about messing with the database. Reza, let me know how you think we should test that

**Comment by rezarzky** [comment]
@andrewjtdunn I just tested on my machine get this error:
Still cant figuring out what's going on
```
[24504:0417/175400.659:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[24504:0417/175400.659:ERROR:disk_cache.cc(208)] Unable to create cache
```

It's okay to mess around with the database, I will do clean up after we set up our code

**Comment by andrewjtdunn** [comment]
@rezarzky working in this branch

**Comment by andrewjtdunn** [comment]
Places that need error handling and potentially testing:

- [ ] no federal register page or text for a document
- [ ] documents open for commenting on regulations.gov which don't have a docket (eg FRS-2024-0019-0001)
- [ ] (the longer list we generated on Friday)
