### ISSUE TITLE
manage when we hit API limit on regulations.gov API calls

### ISSUE THREAD

**Issue by andrewjtdunn** [uchicago-capp-30320/CivicLens#54]
response we get is: [<Response [429]>, 429]
{‘error’: {‘code’: ‘OVER_RATE_LIMIT’, ‘message’: ‘You have exceeded your rate limit. Try again later or contact us at https://www.regulations.gov/support for assistance’}}

could be handled in move_data_from_api_to_database or access_api_data

**Comment by GregoryHo88** [comment]
Incorporated waiting till rate limit reset

**Comment by andrewjtdunn** [comment]
@GregoryHo88 is this issue resolved? If so, can you close the issue?

**Comment by GregoryHo88** [comment]
Yes it is. My apologies
