### ISSUE TITLE
Postgres table for NLP analysis

### ISSUE THREAD

**Issue by jgibson517** [uchicago-capp-30320/CivicLens#73]
Possible Fields:
- Document ID (primary key)
- Docket ID
- Plain English Title
- Representative Comments

**Comment by andrewjtdunn** [comment]
Wouldn't you want document ID as the primary key? We're summarizing on the document level, right?

**Comment by andrewjtdunn** [comment]
@jgibson517 @abejburton if you give me a draft idea of columns and data type for each, I will make a table

**Comment by andrewjtdunn** [comment]
**Table**: rows are documents

**Columns**:
doc_id
rep_comments (contains nested dicts)
doc_plain_english_title 
total_number_comments
total_unique_comments
total_representative_comments
topics (contains nested dicts)
total_number_topics
comments_last_updated (date)
nlp_last_updated (date)
