### ISSUE TITLE
test(s) to capture the front end/back end connection

### ISSUE THREAD

**Issue by jchristensonCHI** [uchicago-capp-30320/CivicLens#87]
- [ ] Create a test to capture the database, to Django, to frontend connection for documents
- [ ] Create a test to capture the database, to Django, to frontend connection for comments

Potential sudo code for the test:

```
def test_document_response(doc_id):
    # get html of website with a request (use django config for the URL to request)
    response = requests.get(url, doc_id)
    #test if the container with the id has the right doc_id (do some webscraping to check)
```

**Comment by claireboyd** [comment]
figure out django documentation for test db
