### ISSUE TITLE
Within regulations_document, lots of "NULL" values and "Not Found" in fr_doc_num and agency_id columns

### ISSUE THREAD

**Issue by jchristensonCHI** [uchicago-capp-30320/CivicLens#96]

**Comment by jchristensonCHI** [comment]
Talked to Andrew about this and posted the issue as he asked.  What I saw in the PostgreSQL database:
<img width="1532" alt="Screenshot 2024-05-01 at 5 24 52 PM" src="https://github.com/uchicago-capp-30320/CivicLens/assets/114839369/787f5122-cc32-4060-b6d4-a2e89c4a30eb">

**Comment by andrewjtdunn** [comment]
Saying this explicitly: issue is that some of the columns _appear_ to not match the column headers. If so, this suggests that something in the data upload process is misaligned

**Comment by GregoryHo88** [comment]
1.) lots of "NULL" values and "Not Found" in fr_doc_num and agency_id 
- @jchristensonCHI, it seems reasonable to expect these discrepancies as not all documents uploaded to regulations.gov are archived in the Federal Register.

2.) Some row values appear not to match column headers.
- I will conduct further tests and investigate this issue more thoroughly.

**Comment by rezarzky** [comment]
Checked on 3 API, not all of them have fr_doc_num

**Comment by andrewjtdunn** [comment]
discussion as of today:

- [ ] build out QA checks on document data (and ideally docket and comment data)
- [ ] extract list of document ids in the regulations_document table
- [ ] re-pull document data and update in the regulations_document table
