### ISSUE TITLE
add functionality to remove documents that are no longer open for comment from site

### ISSUE THREAD

**Issue by andrewjtdunn** [uchicago-capp-30320/CivicLens#98]
I think this should be handled in a nightly cronjob -- if we're past the comment submission due date, somehow take down the document and its comments

**Comment by andrewjtdunn** [comment]
any thoughts about how to do this @rezarzky?

**Comment by andrewjtdunn** [comment]
Note: some documents have None as the value for commentEndDate. Presumably this gets changed at some point, but we wouldn't catch it unless we're checking for changes in the document data.

**Comment by andrewjtdunn** [comment]
@rezarzky can you address this issue? is this resolved?

**Comment by rezarzky** [comment]
Yes, on my last PR
